FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10

RUN microdnf -y install python3 \
 && microdnf clean all \
 && mkdir -p /srv \
 && chmod 755 /srv

COPY index.html /srv/index.html

WORKDIR /srv
EXPOSE 8080
USER 1001
CMD ["python3", "-m", "http.server", "8080", "--bind", "0.0.0.0"]
