{{- /* Pattern path creates the OperatorGroup with the values-hub subscription. */}}
{{- if and .Values.mta.enabled .Values.mta.subscription.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "mta-demo.fullname" . }}-mta
  labels:
    {{- include "mta-demo.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
{{- end }}
